
# title: Yifan (Tiffany) Hu
# #logo: /assets/23fcb415b6258a21c6382f7808c9e72c.JPG
# show_downloads: false
# theme: jekyll-theme-minimal

title: 
email: 
description: Welcome to my personal website! I'm Tiffany Hu, a passionate data scientist and researcher dedicated to uncovering insights from data and creating impactful solutions.
baseurl: ""
url: "https://yifanhu.me"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github_username: Tiff-Hu

# Social links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/tiffany-hu-career1101/
  - name: GitHub
    url: https://github.com/Tiff-Hu
  

# Navigation
navigation:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Projects
    link: /projects/
  - name: Contact
    link: /contact/

# Footer customization
footer: |
  © 2024 Tiffany Hu. All rights reserved.
  Built with ❤️ using Jekyll and the Midnight theme.






